### ISSUE TITLE
invalid dts generation

### ISSUE THREAD

**Issue by kalvenschraut** [rolldown/tsdown#372]
### Reproduction link or steps

https://github.com/RTVision/invalid-dts-generation

follow readme

### What is expected?

no type errors from generated dts.
typing output similar to tsc or one without errors

<img width="740" height="109" alt="Image" src="https://github.com/user-attachments/assets/4c378023-1c98-4290-b15a-c8532727645e" />

### What is actually happening?

type errors when file is opened and cant use that dts to typecheck code that depends on that .d.ts file.

<img width="900" height="176" alt="Image" src="https://github.com/user-attachments/assets/a0bc4182-ef74-49bb-b184-00bc62dea686" />

I do not expect the void 0 to be there

### Any additional comments?

I do not think it is a problem with tsdown, but not sure if it is rolldown-dts or oxc issue. Starting here for now

**Comment by kalvenschraut** [comment]
While trying work around this issue I noticed using tsgo, or forcing tsc by setting isolatedDeclarations to false does not result in a fix so thinking the issue is either in tsdown or more likely rolldown-dts. I did use tsgo stand alone and it did not have an issue just to double check

**Comment by Boshen** [comment]
cc @Dunqing That annoying `this` is causing trouble, waiting for https://github.com/oxc-project/oxc/pull/12156

**Comment by Boshen** [comment]
This is fixed in the latest version of rolldown.

**Comment by kalvenschraut** [comment]
<img width="1031" height="412" alt="Image" src="https://github.com/user-attachments/assets/5be4ee1d-cd7c-4852-a48b-2f262de9672c" />
@Boshen  this is still a problem in my same repo, I updated to latest tsdown which uses rolldown beta 41

**Comment by sxzz** [comment]
Fixed in `rolldown-plugin-dts@0.16.10`

**Comment by kalvenschraut** [comment]
confirmed fix for me, thanks @sxzz!
