### ISSUE TITLE
subsequent dts changes are not written to output dir in watch mode

### ISSUE THREAD

**Issue by telcy** [rolldown/tsdown#396]
### Reproduction link or steps

https://stackblitz.com/edit/stackblitz-starters-pw2y7uwz

1. `npm run dev`
2. use the different export comments and check output dir

### What is expected?

all dts changes should be written to output dir

### What is actually happening?

subsequent dts changes are not written to output dir
only js changes are written to output dir

**Comment by ekzhang** [comment]
I have been seeing this bug as well. A workaround is to add this to your `tsdown.config.ts`:

```js
  dts: {
    // Without newContext, dts generation in watch mode has trouble updating
    // when files are changed.
    newContext: true,
  },
```

This only affects the .d.ts files, the .ts files and chunks change fine. Also the mtime is updated on the dts files but the contents themselves do not change.

Reference: https://github.com/sxzz/rolldown-plugin-dts/commit/9ea4b95877d38e4b1ad6f7f0eb67f046f271cb6c

**Comment by ryan-zayne** [comment]
I've seen this bug come and go between multiple version updates (currently present in v0.13.0)

downgrading to v0.12.9 works for me

**Comment by sxzz** [comment]
Fixed via 0c7ab92c325ed7dea3f88469522af041170cd2fd (not tested on Windows)

**Comment by ekzhang** [comment]
Hmm, I can still reproduce this bug on tsdown `0.13.2` with multiple builds formats, need `newContext: true`. I'm having a hard time reproducing on StackBlitz though, something about the WASI backend doesn't work with watch mode on multiple build formats I think.

**Comment by sxzz** [comment]
You can try to upload reproduction via a GitHub repo.
